### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by ArpitPy** [mayank0274/Lets-talk#5]
Where did you host this project?
I tried using vercel for hosting backend but it giving 404.
Also do i replace all localhost:3000 with hosted api link?

**Comment by mayank0274** [comment]
i have used render.
Also make sure that is Vercel support hosting with websockets and you have configured.env file properly

**Comment by ArpitPy** [comment]
I added:
VITE_CLOUDINARY_CLOUD_NAME=""
VITE_CLOUDINARY_UPLOAD_PRESET=""
in .env file
Do i need to add anything else?

**Comment by ArpitPy** [comment]
I am getting unexpected end of JSON error

**Comment by ArpitPy** [comment]
I am getting this error when i try to login: "Unexpected token '<', "<!DOCTYPE "... is not valid JSON"

**Comment by mayank0274** [comment]
> I added: VITE_CLOUDINARY_CLOUD_NAME="" VITE_CLOUDINARY_UPLOAD_PRESET="" in .env file Do i need to add anything else?

these are for frontend you can get these values from cloudinary dashboard

here i am talking about env variables of backend (.env.example file of this repo ), try to check your api with postman or some api client

have you chage vite.config.js , proxy for api to your api link

**Comment by ArpitPy** [comment]
Yes I added all those fields, I didn't understand what to add in JWT_SECRET, so i added a random string in that.
Yup i properly added api link to vite.config.js as well as in all other places as present in local files.

**Comment by mayank0274** [comment]
after deoloyment frontend  proxy api not works , you have to specify redirects ( i have used this for netlify ) , for vercel i think this helps you 
https://stackoverflow.com/questions/73267938/proxy-api-is-not-working-in-vite-vue-3-project-when-its-deployed-to-vercel 

OR change requests url to complete one like this for all ( <your_api_url>/api/auth/login )

**Comment by ArpitPy** [comment]
I moved to netlify as well 😂

**Comment by mayank0274** [comment]
> I moved to netlify as well 😂

😂😂, do not forget to add "_reditects" file with redirects rules to root of your build folder , otherwise you get error again

**Comment by ArpitPy** [comment]
Alright...

Name:_redirects
Content:
/api*  https://hostedapi.com/api/:splat 200

is this correct or do i need to add anything else?

**Comment by mayank0274** [comment]
/api/*  https://hostedapi.com/api/:splat  200
/* /index.html 200

just add upper lines to _redirects files

**Comment by ArpitPy** [comment]
Did you setup SSH for render?

**Comment by mayank0274** [comment]
> Did you setup SSH for render?

no

**Comment by ArpitPy** [comment]
![image](https://github.com/mayank0274/Lets-talk/assets/71400381/2fe03d2f-aac3-4d4d-b839-4f79d79a9d16)
![image](https://github.com/mayank0274/Lets-talk/assets/71400381/9cfe85de-9b8a-43e0-baa0-dccc1dde3a6e)
This is the error i am getting...🫠😞

**Comment by mayank0274** [comment]
> ![image](https://user-images.githubusercontent.com/71400381/260244355-2fe03d2f-aac3-4d4d-b839-4f79d79a9d16.png) ![image](https://user-images.githubusercontent.com/71400381/260244375-9cfe85de-9b8a-43e0-baa0-dccc1dde3a6e.png) This is the error i am getting...🫠😞

check network tab of developers tools is request sent to correct url and check console if any error there

**Comment by ArpitPy** [comment]
![image](https://github.com/mayank0274/Lets-talk/assets/71400381/f4dec558-46e5-4908-a71f-6af028a80e92)
No error over there

**Comment by mayank0274** [comment]
send login request while opening network tab and then check response, request data

**Comment by ArpitPy** [comment]
Yup that's what i did

**Comment by ArpitPy** [comment]
![image](https://github.com/mayank0274/Lets-talk/assets/71400381/e5283525-b518-4db3-915c-41260d6e8caf)
it shows error occuring here

**Comment by mayank0274** [comment]
> ![image](https://user-images.githubusercontent.com/71400381/260245739-e5283525-b518-4db3-915c-41260d6e8caf.png) it shows error occuring here

any error message/ log associated with it ?

**Comment by ArpitPy** [comment]
There is error in console it gives 404
& it is making POST request to: frontendlink/api/auth/login

**Comment by ArpitPy** [comment]
It should make post req to backend link right?

**Comment by mayank0274** [comment]
> It should make post req to backend link right?

ya , have you done it? https://github.com/mayank0274/Lets-talk/issues/5#issuecomment-1675992657

**Comment by ArpitPy** [comment]
In frontend, i have properly put api link in:
socketConnection.js and vite.config.js
But still.......
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  server: {
    proxy: {
      "/api": "https://backend.onrender.com",
    },
  },
  plugins: [react()],
});
```

**Comment by mayank0274** [comment]
is it working locally ?

**Comment by ArpitPy** [comment]
yess

**Comment by ArpitPy** [comment]
![image](https://github.com/mayank0274/Lets-talk/assets/71400381/7f8dd570-7b38-4335-a88d-768707b2d686)

**Comment by mayank0274** [comment]
![Uploading IMG_20230812_224525.jpg…]()

are you seeing this on deploy summary of netlify

**Comment by ArpitPy** [comment]
Image not loading...

**Comment by mayank0274** [comment]
> Image not loading...

see this https://ibb.co/Hz9j8b3

**Comment by ArpitPy** [comment]
![image](https://github.com/mayank0274/Lets-talk/assets/71400381/43ab219e-e804-496f-8a4d-f5c8570e79a7)
No it does not

**Comment by ArpitPy** [comment]
But i added it...
![image](https://github.com/mayank0274/Lets-talk/assets/71400381/914e140f-5ecc-458d-9c01-19cb1a1711f8)
![Screenshot 2023-08-12 225727](https://github.com/mayank0274/Lets-talk/assets/71400381/d1d63f32-ee40-4b30-970e-d953fa241781)

**Comment by mayank0274** [comment]
after doing this https://github.com/mayank0274/Lets-talk/issues/5#issuecomment-1675992657
upload build folder again to netlify to update it  , I think you forgot it

**Comment by ArpitPy** [comment]
> But i added it... ![image](https://user-images.githubusercontent.com/71400381/260247909-914e140f-5ecc-458d-9c01-19cb1a1711f8.png) ![Screenshot 2023-08-12 225727](https://user-images.githubusercontent.com/71400381/260247950-d1d63f32-ee40-4b30-970e-d953fa241781.png)

But i have already commited _redirects files, i redeployed but it still did not process them...

**Comment by ArpitPy** [comment]
Do i need to add netlify.toml file?
https://answers.netlify.com/t/redirects-not-being-processed-in-production-works-fine-locally/38106/3

Ohh understood...so i need to put it in build folder

**Comment by mayank0274** [comment]
you are deploying it with GitHub? i think after deployment only content of build folder are getting added and _redirects file not adding ( it can be reason but i have never used GitHub to deploy app to netlify before)

Try to build locally then add _redirects manually and upload that folder via drag n drop or by selecting it

**Comment by ArpitPy** [comment]
> you are deploying it with GitHub? i think after deployment only content of build folder are getting added and _redirects file not adding ( it can be reason but i have never used GitHub to deploy app to netlify before)
> 
> Try to build locally then add _redirects manually and upload that folder via drag n drop or by selecting it

Yup...that should work...let me try

**Comment by ArpitPy** [comment]
Its fixed...works perfectly now!!!
Thanks a lot man!!!!

**Comment by ArpitPy** [comment]
Would you like to connect on linkedin?

**Comment by mayank0274** [comment]
> Would you like to connect on linkedin?

send me your LinkedIn profile link

**Comment by ArpitPy** [comment]
https://www.linkedin.com/in/arpitpandeyofc/

**Comment by ArpitPy** [comment]
> you are deploying it with GitHub? i think after deployment only content of build folder are getting added and _redirects file not adding ( it can be reason but i have never used GitHub to deploy app to netlify before)
> 
> Try to build locally then add _redirects manually and upload that folder via drag n drop or by selecting it

So basically,
If you are uploading by making a build folder, you must put _redirects file
Or else, if you are deploying via github, you should include netlify.toml file in root folder
